<?php

namespace App;

use App\Scopes\IsActiveScope;
use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $table = 'teachers';
    protected $connection = 'academic';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new IsActiveScope);
    }


    public function classes(){
        return $this->hasMany(AcadClass::class,'TEACHERCODE','CODE');
    }
}
